steps:
  build:
    image: hexpm/elixir:1.14.5-erlang-25.3.2.5-debian-buster-20230612-slim
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - apt-get update
      - apt-get install -y libgpgme-dev
      - curl https://sh.rustup.rs -sSf | bash -s -- -y
      - source ~/.cargo/env
      - rustc -V
      - mix compile --warnings-as-errors
