baseURL                  = "https://silbernagel.dev/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "silbernagel.dev"
theme                    = "pulp"
pygmentsStyle            = "monokai"
pygmentsCodefences       = true
pygmentsUseClasses       = false
relativeURLs             = true
disqusShortName          = "silbernagel-dev"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
    author               = "Matt Silbernagel"
    dateform             = "Mon Jan 02, 2006"
    avatar               = "avatar.jpg"
    favicon              = "favicon.ico"
    homepage             = "main"
    description          = ""
    title                = "silbernagel.dev"
    publicationYear      = "2019"

[[menu.main]]
    identifier = "posts"
    name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "presentations"
    name = "Presentations"
    pre = "<i class='fa fa-file-powerpoint fa-lg'></i>"
    url = "/presentations/"
    weight = 20

[[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/silbermm"
    weight = 30

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/silbermm"
    weight = 40

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/presentations"
    text = "presentations"


[imaging]
    quality = 75
