baseURL                  = "https://silbernagel.dev/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "silbernagel.dev"
theme                    = "anatole"
pygmentsCodefences       = true
pygmentsUseClasses       = false
relativeURLs             = true
disqusShortname          = "silbernagel-dev"

[taxonomies]
  category = "categories"
  tag      = "tags"
  series   = "series"

[params]
    author               = "Matt Silbernagel"
    dateform             = "Mon Jan 02, 2006"
    profilePicture       = "img/avatar.jpg"
    favicon              = "favicon.ico"
    homepage             = "main"
    description          = ""
    title                = ""
    publicationYear      = "2021"
    displayMode          = "dark"
    doNotLoadAnimations  = true
    contentratio         = 0.8
    customCss            = ["css/code.css"]
    images               = ["img/avatar.jpg"]
    disableThemeSwitcher = true
    mainSections         = ["posts"]
    enableMediumZoom     = false
    postSectionName      = "posts"

[[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = 10

[[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = 15

[[menu.main]]
    identifier = "presentations"
    name       = "Presentations"
    url        = "/presentations/"
    weight     = 20

[[menu.footer]]
    title = "Powered by the Interplanetary Filesystem"
    url   = "https://ipfs.io"
    name  = "Powered by the Interplanetary Filesystem"


[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/presentations"
    text = "presentations"

[[params.socialIcons]]
  icon  = "fab fa-twitter"
  title = "Twitter"
  url   = "https://twitter.com/silbermm"

[[params.socialIcons]]
  icon  = "fab fa-github"
  title = "Github"
  url   = "https://github.com/silbermm"

[[params.socialIcons]]
  icon  = "fas fa-key"
  title = "GPG Public Key"
  url   = "/silbernagel.pgp"

[imaging]
    quality = 75
